import importlib.util
import json
from pathlib import Path
import shutil
import subprocess
import tempfile
import textwrap
import unittest


REPO_ROOT = Path(__file__).resolve().parents[1]
BUILD_SCRIPT = REPO_ROOT / 'builder' / 'build_sd.py'
WEB_BUILDER = REPO_ROOT / 'docs' / 'app' / 'index.html'


def load_builder_module():
    spec = importlib.util.spec_from_file_location('mmi3g_build_sd_web_run_sh', BUILD_SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def extract_function(source: str, name: str) -> str:
    async_token = f'async function {name}('
    token = f'function {name}('
    start = source.index(async_token) if async_token in source else source.index(token)
    brace = source.index('{', start)
    depth = 0
    in_str = None
    escape = False
    in_line_comment = False
    in_block_comment = False
    i = brace

    while i < len(source):
        ch = source[i]
        nxt = source[i + 1] if i + 1 < len(source) else ''
        if in_line_comment:
            if ch == '\n':
                in_line_comment = False
        elif in_block_comment:
            if ch == '*' and nxt == '/':
                in_block_comment = False
                i += 1
        elif in_str:
            if escape:
                escape = False
            elif ch == '\\':
                escape = True
            elif ch == in_str:
                in_str = None
        else:
            if ch == '/' and nxt == '/':
                in_line_comment = True
                i += 1
            elif ch == '/' and nxt == '*':
                in_block_comment = True
                i += 1
            elif ch in ('"', "'", '`'):
                in_str = ch
            elif ch == '{':
                depth += 1
            elif ch == '}':
                depth -= 1
                if depth == 0:
                    return source[start:i + 1]
        i += 1

    raise RuntimeError(f'failed to extract {name}')


class WebRunShParityTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        node = shutil.which('node')
        if node is None:
            raise unittest.SkipTest('node is not installed')

        cls.node = node
        cls.builder = load_builder_module()
        cls.modules = cls.builder.find_modules()
        cls.web_source = WEB_BUILDER.read_text(encoding='utf-8')
        cls.generate_run_sh_js = extract_function(cls.web_source, 'generateRunSh')

    def render_web_run_sh(self, selected):
        node_script = textwrap.dedent(
            f'''
            const fs = require('node:fs');
            const vm = require('node:vm');
            const manifest = JSON.parse(fs.readFileSync('docs/app/manifest.json', 'utf8'));
            const sandbox = {{}};
            vm.createContext(sandbox);
            vm.runInContext({json.dumps(self.generate_run_sh_js)}, sandbox);
            process.stdout.write(sandbox.generateRunSh({json.dumps(selected)}, manifest));
            '''
        )

        with tempfile.NamedTemporaryFile('w', suffix='.js') as script:
            script.write(node_script)
            script.flush()
            return subprocess.run(
                [self.node, script.name],
                cwd=str(REPO_ROOT),
                check=True,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            ).stdout

    def normalize_run_sh(self, text):
        lines = []
        for line in text.splitlines():
            if line.startswith('# Auto-generated by'):
                continue
            lines.append(line.rstrip())
        return '\n'.join(lines).strip()

    def test_generate_run_sh_matches_python_builder_for_representative_modules(self):
        representative_sets = (
            ['system-info'],
            ['gem-activator', 'can-scanner'],
            ['diag-tool'],
            ['per3-reader'],
            ['lte-setup'],
        )

        for selected in representative_sets:
            with self.subTest(selected=selected):
                self.assertEqual(
                    self.normalize_run_sh(
                        self.builder.generate_run_sh(selected, self.modules)
                    ),
                    self.normalize_run_sh(self.render_web_run_sh(selected)),
                )


if __name__ == '__main__':
    unittest.main()
