SETTINGS {
	;Transfer timeout when under 500 bytes for 10 second
	Connection/minTransferRate = 500
	Connection/minTransferRateTime = 10

    ; Don't keep in memory copy of textures.
    discardOriginalTextureImages = true
    enableMipmaps = true
    disableAnisotropicFiltering = false
    enableVertexBufferObjects = true

    Connection/enableSeamlessLogin = true

    Planet/alternateFocusPoint = false

    ; Render options
    Render/textureCompressionDXTC = true
    Render/forceDrawablesOnWorkQueue = false
    Render/recommendedVertsPerArray = 4096
    Render/forceSleep = false
    Render/lockOnFrameRate = false

    ; Road rendering options
    RoadRendering/LineControllerRequiresStyle = false
    RoadRendering/EnableCarNavigationPOI = true

    ; Drawable options
    Drawables/drawableOffset = 0.1
    Drawables/iconScale = 1.5
    Drawables/nearClamp = 0.9

    ; Cache settings
    DiskCache/cacheSize = 1800
    DiskCache/touchStorageEntries = true

    Network/maxRequestsBacklog = 10

    ;Debug/enableMemoryBarGraph = true
    ;Debug/memoryBarGraphRange = 128
    ;Debug/frameStatsState = true

}
