"""
MMI3G-Toolkit SD Card Builder

Assembles selected modules into a complete, ready-to-use SD card package
for Audi/VW MMI3G, MMI3G+, and RNS-850 infotainment systems.

Usage:
    python build_sd.py --list                    List available modules
    python build_sd.py --all -o ./sdcard         Build with all modules
    python build_sd.py -m gauges-dashboard -m system-info -o ./sdcard
    python build_sd.py -m gauges-dashboard -o F:  Build directly to SD card

The builder:
  1. Copies core files (encoded copie_scr.sh, run.sh)
  2. Copies selected module files (engdefs, scripts)
  3. Generates a combined run.sh that installs all selected modules
  4. Creates the required directory structure (bin, lib, var)
"""

import argparse
import json
import os
import shutil
import sys

# Resolve paths relative to this script
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)
MODULES_DIR = os.path.join(REPO_ROOT, 'modules')
CORE_DIR = os.path.join(REPO_ROOT, 'core')


def find_modules() -> dict:
    """Discover all available modules."""
    modules = {}
    if not os.path.isdir(MODULES_DIR):
        return modules
    
    for name in sorted(os.listdir(MODULES_DIR)):
        mod_dir = os.path.join(MODULES_DIR, name)
        meta_file = os.path.join(mod_dir, 'module.json')
        if os.path.isdir(mod_dir) and os.path.isfile(meta_file):
            with open(meta_file, 'r') as f:
                meta = json.load(f)
            meta['_dir'] = mod_dir
            meta['_name'] = name
            modules[name] = meta
    
    return modules


def list_modules(modules: dict):
    """Print available modules."""
    print("Available modules:")
    print("=" * 60)
    for name, meta in modules.items():
        status = "ready" if meta.get('status') == 'ready' else meta.get('status', 'unknown')
        compat = ', '.join(meta.get('compatible', ['MMI3G+']))
        print(f"  {name}")
        print(f"    {meta.get('description', 'No description')}")
        print(f"    Status: {status} | Compatible: {compat}")
        print()


def generate_run_sh(selected_modules: list, modules: dict) -> str:
    """Generate the combined run.sh for selected modules."""
    
    lines = [
        '#!/bin/ksh',
        '# ============================================================',
        '# MMI3G-Toolkit - Combined Installer',
        '# Auto-generated by build_sd.py',
        '# ============================================================',
        '',
        'SDPATH="${1:-$(dirname $0)}"',
        'LOGFILE="${SDPATH}/var/install-$(date +%Y%m%d-%H%M%S).log"',
        'EFSDIR="/mnt/efs-system"',
        'ENGDEFS="${EFSDIR}/engdefs"',
        '',
        'exec > ${LOGFILE} 2>&1',
        '',
        'echo "============================================"',
        'echo " MMI3G-Toolkit Installer"',
        'echo " $(date)"',
        'echo " Train: $(cat /dev/shmem/sw_trainname.txt 2>/dev/null)"',
        'echo "============================================"',
        'echo ""',
        '',
        '# Safety checks',
        'if [ ! -d "${EFSDIR}" ]; then',
        '    echo "[ERROR] /mnt/efs-system not found!"',
        '    exit 1',
        'fi',
        '',
        'if [ ! -d "${ENGDEFS}" ]; then',
        '    echo "[ERROR] engdefs not found. Enable GEM first."',
        '    exit 1',
        'fi',
        '',
        '# Remount read-write',
        'mount -uw ${EFSDIR}',
        'if [ $? -ne 0 ]; then',
        '    echo "[ERROR] Failed to remount efs-system"',
        '    exit 1',
        'fi',
        'echo "[OK] efs-system remounted rw"',
        'echo ""',
        '',
    ]
    
    # Add install section for each module
    for mod_name in selected_modules:
        meta = modules[mod_name]
        lines.append(f'# --- Module: {mod_name} ---')
        lines.append(f'echo "[MODULE] Installing {mod_name}..."')
        
        # Check if module has a standalone run script
        # (e.g. gem-activator runs its own install logic)
        if meta.get('standalone') and meta.get('run_script'):
            run_script = meta['run_script']
            lines.append(f'if [ -f "${{SDPATH}}/scripts/{run_script}" ]; then')
            lines.append(f'    ksh "${{SDPATH}}/scripts/{run_script}" "${{SDPATH}}"')
            lines.append(f'    echo "[OK] {mod_name} standalone script executed"')
            lines.append(f'else')
            lines.append(f'    echo "[WARN] {run_script} not found for {mod_name}"')
            lines.append(f'fi')
            
            # Also install scripts to flash for future use from GEM
            scripts_dir = os.path.join(meta['_dir'], 'scripts')
            if os.path.isdir(scripts_dir):
                script_dest = meta.get('script_dir', f'/scripts/{mod_name}')
                lines.append(f'SCRIPTDIR="${{EFSDIR}}{script_dest}"')
                lines.append(f'mkdir -p ${{SCRIPTDIR}}')
                for script in sorted(os.listdir(scripts_dir)):
                    if script.endswith('.sh'):
                        lines.append(f'if [ -f "${{SDPATH}}/scripts/{script}" ]; then')
                        lines.append(f'    cp -v "${{SDPATH}}/scripts/{script}" "${{SCRIPTDIR}}/{script}"')
                        lines.append(f'    chmod +x "${{SCRIPTDIR}}/{script}"')
                        lines.append(f'fi')
        else:
            # Standard module — install engdefs and scripts
            
            # Install engdefs
            lines.append(f'if [ -d "${{SDPATH}}/engdefs" ]; then')
            
            mod_dir = modules[mod_name]['_dir']
            engdefs_dir = os.path.join(mod_dir, 'engdefs')
            if os.path.isdir(engdefs_dir):
                for esd in sorted(os.listdir(engdefs_dir)):
                    if esd.endswith('.esd'):
                        lines.append(f'    if [ -f "${{SDPATH}}/engdefs/{esd}" ]; then')
                        lines.append(f'        cp -v "${{SDPATH}}/engdefs/{esd}" "${{ENGDEFS}}/{esd}"')
                        lines.append(f'        echo "[INST] {esd}"')
                        lines.append(f'    fi')
            
            lines.append('fi')
            
            # Install scripts
            scripts_dir = os.path.join(mod_dir, 'scripts')
            if os.path.isdir(scripts_dir):
                script_dest = meta.get('script_dir', f'/scripts/{mod_name}')
                lines.append(f'SCRIPTDIR="${{EFSDIR}}{script_dest}"')
                lines.append(f'mkdir -p ${{SCRIPTDIR}}')
                lines.append(f'if [ -d "${{SDPATH}}/scripts" ]; then')
                
                for script in sorted(os.listdir(scripts_dir)):
                    if script.endswith('.sh'):
                        lines.append(f'    if [ -f "${{SDPATH}}/scripts/{script}" ]; then')
                        lines.append(f'        cp -v "${{SDPATH}}/scripts/{script}" "${{SCRIPTDIR}}/{script}"')
                        lines.append(f'        chmod +x "${{SCRIPTDIR}}/{script}"')
                        lines.append(f'        echo "[INST] {script}"')
                        lines.append(f'    fi')
                
                lines.append('fi')
        
        lines.append(f'echo "[OK] {mod_name} installed"')
        lines.append('echo ""')
        lines.append('')
    
    # Summary
    lines.extend([
        '# --- Complete ---',
        'sync',
        'echo "============================================"',
        'echo " Installation Complete"',
        f'echo " Modules installed: {len(selected_modules)}"',
        'echo " Log: ${LOGFILE}"',
        'echo ""',
        'echo " Open GEM (CAR + BACK) to access new screens"',
        'echo "============================================"',
    ])
    
    return '\n'.join(lines) + '\n'


def build_sd(selected_modules: list, modules: dict, output_dir: str):
    """Build the SD card contents."""
    
    print(f"Building SD card -> {output_dir}")
    print(f"Modules: {', '.join(selected_modules)}")
    print()
    
    # Create directory structure
    for d in ['bin', 'lib', 'var', 'engdefs', 'scripts']:
        os.makedirs(os.path.join(output_dir, d), exist_ok=True)
    
    # Encode and copy copie_scr.sh
    template_path = os.path.join(CORE_DIR, 'copie_scr_plain.sh')
    if os.path.isfile(template_path):
        from encoder import MMI3GCipher
        
        with open(template_path, 'rb') as f:
            plaintext = f.read()
        
        cipher = MMI3GCipher()
        encoded = cipher.process(plaintext)
        
        copie_out = os.path.join(output_dir, 'copie_scr.sh')
        with open(copie_out, 'wb') as f:
            f.write(encoded)
        print(f"  [OK] copie_scr.sh encoded ({len(encoded)} bytes)")
    else:
        print(f"  [WARN] {template_path} not found - you'll need to add copie_scr.sh manually")
    
    # Copy module files
    for mod_name in selected_modules:
        meta = modules[mod_name]
        mod_dir = meta['_dir']
        
        # Copy engdefs
        engdefs_src = os.path.join(mod_dir, 'engdefs')
        if os.path.isdir(engdefs_src):
            for f in os.listdir(engdefs_src):
                if f.endswith('.esd'):
                    shutil.copy2(
                        os.path.join(engdefs_src, f),
                        os.path.join(output_dir, 'engdefs', f)
                    )
                    print(f"  [OK] engdefs/{f}")
        
        # Copy scripts
        scripts_src = os.path.join(mod_dir, 'scripts')
        if os.path.isdir(scripts_src):
            for f in os.listdir(scripts_src):
                if f.endswith('.sh'):
                    shutil.copy2(
                        os.path.join(scripts_src, f),
                        os.path.join(output_dir, 'scripts', f)
                    )
                    print(f"  [OK] scripts/{f}")
    
    # Generate combined run.sh
    run_sh = generate_run_sh(selected_modules, modules)
    run_path = os.path.join(output_dir, 'run.sh')
    with open(run_path, 'w', newline='\n') as f:
        f.write(run_sh)
    print(f"  [OK] run.sh generated")
    
    # Copy uninstall script
    uninstall_src = os.path.join(CORE_DIR, 'uninstall.sh')
    if os.path.isfile(uninstall_src):
        shutil.copy2(uninstall_src, os.path.join(output_dir, 'uninstall.sh'))
        print(f"  [OK] uninstall.sh")
    
    print()
    print("=" * 50)
    print("SD card build complete!")
    print()
    print("To use:")
    print("  1. Format 32GB SDHC as FAT32")
    print(f"  2. Copy contents of {output_dir}/ to card root")
    print("  3. Boot MMI fully, then insert SD card")
    print("  4. Wait 30s, remove card")
    print("  5. Open GEM (CAR + BACK) to see new screens")


def main():
    parser = argparse.ArgumentParser(
        description='MMI3G-Toolkit SD Card Builder',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s --list                         List available modules
  %(prog)s --all -o ./sdcard              Build with everything
  %(prog)s -m gauges-dashboard -o F:\\     Build to SD card drive
  %(prog)s -m gauges-dashboard -m system-info -o ./sdcard
        """
    )
    
    parser.add_argument('--list', action='store_true',
                        help='List available modules')
    parser.add_argument('-m', '--module', action='append', dest='modules',
                        help='Module to include (can specify multiple)')
    parser.add_argument('--all', action='store_true',
                        help='Include all ready modules')
    parser.add_argument('-o', '--output', default='./sdcard',
                        help='Output directory (default: ./sdcard)')
    
    args = parser.parse_args()
    
    available = find_modules()
    
    if not available:
        print("No modules found! Check that the modules/ directory exists.")
        sys.exit(1)
    
    if args.list:
        list_modules(available)
        return
    
    # Determine which modules to build
    if args.all:
        selected = [n for n, m in available.items() if m.get('status') == 'ready']
    elif args.modules:
        selected = []
        for m in args.modules:
            if m not in available:
                print(f"Unknown module: {m}")
                print(f"Available: {', '.join(available.keys())}")
                sys.exit(1)
            selected.append(m)
    else:
        parser.print_help()
        sys.exit(1)
    
    if not selected:
        print("No modules selected!")
        sys.exit(1)
    
    build_sd(selected, available, args.output)


if __name__ == '__main__':
    main()
